### ISSUE TITLE
How to deserialize operators?

### ISSUE THREAD

**Issue by LasmGratel** [rakaly/jomini#105]
e.g. a modifier list:

```
modifier = {
	factor = 2
	has_policy_flag = economic_stance_market
}
modifier = {
	factor = 0
	num_communications < 2
}
```

I know TextTape can do this, but I don't know how to mix TextTape and struct together. I tried JominiDeserialize and serde's visitor, but neither `Operator` nor `OperatorValue` implements `Deserialize`.

**Comment by nickbabcock** [comment]
Thank you for bringing this up, your input on how to handle this would be appreciated.

Currently operators on struct deserialization are ignored as keys of a struct are implicitly equal to their values (and serde doesn't have any primitives for working with non-equal operators).

As a comparison, the JSON module will preserve operators

```
foo > bar
```

And translate it into

```json
{"foo":{"GREATER_THAN":"bar"}}
```

I've not been entirely convinced by this output to port it over to deserialization, as there are other ways operators can be represented (like a two element array, for instance):

```json
{"foo":[">","bar"]}
```

I'm assuming the end goal is to have a struct like:

```rust
struct jomini::de::Property<T> {
  pub operator: Operator,
  pub value: T 
}

// ...

struct Modifier {
  factor: i32,
  num_communications: Property<i32>,
}
```

I think this is possible, I just need to mull over how to add this option to `TextDeserializer` and how to implement deserialize for `Property<T>`. I have a few ideas, but let me know if you have thoughts on the matter.

**Comment by LasmGratel** [comment]
Thanks for your quick reply.

The property definition looks good to me. A tuple definition is absolutely better than an array(">","1.0").

But it could be a problem to distinguish EQUALS from ASSIGNMENT. Especially when there is a need to flatten to `HashMap<String, Property<String>>`, just like modifiers.

Although I'm not a serde expert, it seems that it can be solved by specifically implementing `visit_map`.

Parsing modifiers could be a tough task

----------------------------------------

2022年10月27日 下午7:42:18 Nick Babcock ***@***.***>:

**Comment by nickbabcock** [comment]
How does #106 sound? It introduces a type called `Property` that the deserializer will look for, and if present will deserialize the operator. It's a bit of a hack, but seems useful.
