### ISSUE TITLE
How to debug and handle ScalarError?

### ISSUE THREAD

**Issue by LokiSharp** [rakaly/jomini#115]
When I use the hoi4save parser to parse my HOI4 save file, Jomini returns an "AllDigits Error". This error is likely caused by the fact that the value in the "manpower_pool" field can be a string of numbers with dots, which makes it difficult for the parser to recognize it as valid input.

```
manpower_pool={
	available=95915
	locked=3379.3.22.15
	total=3782.1.21.20
}
```

**Comment by nickbabcock** [comment]
What are you deserializing `locked` and `total` as? The parser can handle numbers and dots just fine 😄 

```rust
#[test]
fn test_deserialize_manpower_pool() {
    #[derive(Deserialize, Debug, PartialEq)]
    struct Root {
        manpower_pool: ManpowerPool,
    }

    #[derive(Deserialize, Debug, PartialEq)]
    struct ManpowerPool {
        available: i32,
        locked: String,
        total: String,
    }

    let data = br#"
    manpower_pool={
        available=95915
        locked=3379.3.22.15
        total=3782.1.21.20
    }
"#;

    let txt_out: Root = jomini::text::de::from_windows1252_slice(&data[..]).unwrap();
    assert_eq!(
        txt_out.manpower_pool,
        ManpowerPool {
            available: 95915,
            locked: String::from("3379.3.22.15"),
            total: String::from("3782.1.21.20"),
        }
    );
}
```

**Comment by nickbabcock** [comment]
I'm not sure what exactly you're looking for, but most everything is possible if you want to write your own deserializer function. Below shows prototype of how you can get rid of the (potentially omitted) dots and interpret the fields as numbers.

```rust
fn deserialize_pool_field<'de, D>(deserializer: D) -> Result<i32, D::Error>
where
    D: Deserializer<'de>,
{
    struct PoolVisitor;

    impl<'de> de::Visitor<'de> for PoolVisitor {
        type Value = i32;

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("a pool field")
        }

        fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            let first = v.split('.').next().unwrap();
            Ok(first.parse::<i32>().unwrap())
        }
    }

    deserializer.deserialize_str(PoolVisitor)
}

#[test]
fn test_deserialize_manpower_pool() {
    #[derive(Deserialize, Debug, PartialEq)]
    struct Root {
        manpower_pool: ManpowerPool,
    }

    #[derive(Deserialize, Debug, PartialEq)]
    struct ManpowerPool {
        available: i32,
        #[serde(deserialize_with = "deserialize_pool_field")]
        locked: i32,
        #[serde(deserialize_with = "deserialize_pool_field")]
        total: i32,
    }

    let data = br#"
    manpower_pool={
        available=95915
        locked=3379.3.22.15
        total=3782
    }
"#;

    let txt_out: Root = jomini::text::de::from_windows1252_slice(&data[..]).unwrap();
    assert_eq!(
        txt_out.manpower_pool,
        ManpowerPool {
            available: 95915,
            locked: 3379,
            total: 3782,
        }
    );
}
```

**Comment by LokiSharp** [comment]
```
manpower_pool={
	available=95915
	locked=73401974
	total=76930819
}
```
Oh, I think there may be a bug in Melt. It would be helpful to set the binary with the debug_saves=1 setting to see if this is true.

**Comment by LokiSharp** [comment]
Here is my saves [https://drive.google.com/file/d/1RAOwDeYgVQgg1XOQa_tN49t5p4dRfoy7/view?usp=sharing](url)

the path is states -> 605 ->manpower_pool

**Comment by nickbabcock** [comment]
Thanks for the saves. It probably is a problem with the melter, as the binary format isn't self descriptive, so we have to rely on heuristics. We've worked around this issue in other games by informing the melter of fields that we either know are dates or know are numbers. I'm assuming we'll be able to do the same fix here 😄

**Comment by LokiSharp** [comment]
Thank you for your response. This save was melted by pdxtools. I tried to melt it with hoi4save, but I received an error message `Error: Hoi4Error(UnknownToken { token_id: 10805 })`. Is there an updated version of hoi4save available?

**Comment by nickbabcock** [comment]
> Thank you for your response. This save was melted by pdxtools. I tried to melt it with hoi4save, but I received an error message `Error: Hoi4Error(UnknownToken { token_id: 10805 })`. Is there an updated version of hoi4save available?

I updated pdx tools, did you want to try it again and let me know if it works?

And yeah when hoi4save is run locally, you need to supply the mapping from binary tokens to text as paradox doesn't allow me to distribute them with the code.

**Comment by LokiSharp** [comment]
Yes, it works. I have created my own token table for melting HOI4 saves. However, when I compared those save files, I encountered a new issue with pdxtools. Some tokens were missing or incorrect, such as 'rk_token_XXX'.

**Comment by LokiSharp** [comment]
This is my own token table [https://drive.google.com/file/d/1NvMnrI3NAOMSunsdxFyExdPgXTK2ifvD/view?usp=share_link](https://drive.google.com/file/d/1NvMnrI3NAOMSunsdxFyExdPgXTK2ifvD/view?usp=share_link)

**Comment by LokiSharp** [comment]
When I use PDX tools to melt my save file, I notice some incorrect tokens such as `rk_token_XXX` and `aurelien_delay_XXX`. For example, the `aurelien_delay_14487` token should be `can_be_fired`, and `rk_token_112` should be `all_playthrough_data`.
