### ISSUE TITLE
Option::unwrap() on a None value

### ISSUE THREAD

**Issue by rlidwka** [rakaly/jomini#137]
I've managed to trigger this unwrap:
https://github.com/rakaly/jomini/blob/797c26e6ef73b0acf0ccad12ce1712e398ba76b3/src/text/de.rs#L409

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\user\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jomini-0.24.0\src\text\de.rs:409:43
```

This is probably my misuse of serde (running `next_value()` on a map twice), but it should be at least an `.expect()` with a better error message or an Error::custom().

Code sample:

```rs
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Color((u8, u8, u8));

#[derive(Deserialize, Debug)]
enum ColorName {
    Red,
    Green,
    Blue,
}

struct Container;

impl<'de> Deserialize<'de> for Container {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct TVisitor;
        impl<'de> serde::de::Visitor<'de> for TVisitor {
            type Value = Container;

            fn expecting(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
                formatter.write_str("{r g b} or name")
            }

            fn visit_map<A: serde::de::MapAccess<'de>>(self, mut map: A) -> Result<Self::Value, A::Error> {
                while let Some(key) = map.next_key::<String>()? {
                    println!("key: {}", key);
                    if let Ok(color) = map.next_value::<Color>() {
                        println!("color: {:?}", color);
                    } else {
                        let name = map.next_value::<ColorName>()?;
                        println!("name: {:?}", name);
                    }
                }
                Ok(Container)
            }
        }
        deserializer.deserialize_map(TVisitor)
    }
}

fn main() {
    let data = r#"
        color1 = red
        color2 = { 255 0 0 }
    "#;
    let _: Container = jomini::text::de::from_utf8_slice(data.as_bytes()).unwrap();
}
```

**Comment by nickbabcock** [comment]
I can look into this. I agree that the behavior is incorrect, `unwrap` should only be used for broken invariants (and, I'm also unclear if multiple calls to `next_value` are valid). In the meantime, can you structure it as an enum like the following test case where you give a hint as to what it could be and then handle both cases.

https://github.com/rakaly/jomini/blob/797c26e6ef73b0acf0ccad12ce1712e398ba76b3/src/text/de.rs#L2082-L2137

If you run into trouble, I can help out further

**Comment by rlidwka** [comment]
> If you run into trouble, I can help out further

No need for help, I solved it by deserializing into `serde-value`, then deserializing that twice. That's probably serde's intended solution.

I just wanted the panic to get fixed in case someone else runs into it. :)

**Comment by nickbabcock** [comment]
Agreed, there should be no panics. I will work on fixing that. Thank you for the test case.
