### ISSUE TITLE
De-serializing enums

### ISSUE THREAD

**Issue by snordgren** [rakaly/jomini#54]
I'd like to de-serialize something like this

```
...
requirements = {
    country = ENG
    prestige = 10
}
...
```

My struct looks like this

```
#[derive(Clone, Debug, Deserialize, PartialEq)]
pub struct Event {
    requirements: Vec<Condition>,
}

#[derive(Clone, Debug, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum Condition {
    Country { country: String },
    Prestige { prestige: u32 }
}
```

But I can't get it to work, with or without named fields in the enums, with or without `untagged`. I'd like to be able to write something like this

```
#[derive(Clone, Debug, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum Condition {
    #[serde(rename="country)]
    Country(String),
    #[serde(rename="prestige")]
    Prestige(u32)
}
```

And have it interpret the 1-field enum alternatives correctly. I wasn't able to use JominiDeserialize with enums either. Is something like this supported?

**Comment by nickbabcock** [comment]
I have this use case too! I work around this by defining a [custom deserialize impl in eu4save](https://github.com/rakaly/eu4save/blob/817be53dce2bd62b5275f3d455525eb2b7ba0161/src/de/war_events.rs). You can do the same thing.

I'm not a serde expert -- does your example work with serde and serde_json? I don't think it does, but I could be mistaken. If it does work, then we have something to base our implementation on, else we'd need to break ground.

This use case keeps coming up, so it's something I want to support, but at least the workaround should suffice in the meantime.

No need to close this issue as this can be used the track the feature request.

**Comment by snordgren** [comment]
Thanks, I will do that for now. I can't figure out how to express this in Serde either, it does not seem to support de-serializing multiple enums tagged by their key from the same object. 

Quite strange considering this pattern is used in JSON as well. Maybe I just don't know the keywords to search for.

**Comment by nickbabcock** [comment]
Turns out this was possible the whole time with enum-maps (checkout the linked pr to know more).
